services:
  - type: web
    name: 95a3e40eb5258097adf
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
